### ISSUE TITLE
Fix master public DNS name parsing problem

### ISSUE THREAD

**Issue by MattBrauer** [hms-dbmi/hail-on-AWS-spot-instances#2]
## The problem

`cloudformation_hail_spot.sh` calls the script `EMR_deploy_and_install_spot.py`, which sets up the cluster, then logs in to install software.

For the login process the IP address that is passed to `ssh` is obtained by a parsing of the `MasterPublicDnsName`. The parsing assumes a DNS name of the form: `ec2-xxx-xxx-xxx-xxx.compute.amazonaws.com` (where `xxx` is an IP address octet), and splits first on `.compute`, then on `ec2-`, then subs `-` with `.`.

However, the DNS name may have additional information, *viz.* `ec2-xxx-xxx-xxx-xxx.us-west-2.compute.amazonaws.com`.

## How to fix

A method more agnostic to the form of the DNS name would simply split on `.`, then on `ec2-`. So:

line 52: `master_IP=re.sub("-",".",master_dns.split(".")[0].split("ec2-")[1])` should replace `master_IP=re.sub("-",".",master_dns.split(".compute")[0].split("ec2-")[1])`

## How this was tested

Uncommented line 55 to print the Master IP derived from the DNS name parsing.

### Before the change

`sh cloudformation_hail_spot.sh` results in a master IP `xxx.xxx.xxx.xxx.us.west.2`

### After the change

`sh cloudformation_hail_spot.sh` results in a master IP `xxx.xxx.xxx.xxx`

**Comment by biocdeniz** [comment]
Agreed and added. Thanks for the feedback @MattBrauer. 
I'm closing this thread.
