### ISSUE TITLE
Fix json error in configurations argument of command in `EMR_deploy_and_install_spot.py`

### ISSUE THREAD

**Issue by MattBrauer** [hms-dbmi/hail-on-AWS-spot-instances#3]
## The problem

Executing the `aws emr` command (with all variable substitutions) leads to notification of an error in the json format of the `--configurations`  argument.

## How to fix

Change the `configurations` argument on line 18 of the `aws emr` command in `EMR_deploy_and_install_spot.py`.

## How this was tested

Ran the script `sh cloudformation_hail_spot.sh` before and after the change. Ran the command following `Your AWS CLI export command:` in both cases. Before the change this resulted in `aws: error: invalid json argument for option --configurations`. After the change resulted in
```
{
    "ClusterId": "j-XXXXXXXXXXXX"
}
```
(where the cluster id is replaced here by Xs).

### Before the change

The original `configurations` argument looks like this (expanded):
```
--configurations 
[
  {
    "Classification":"spark",
    "Properties":{"maximizeResourceAllocation":"true"},
    "Classification":"yarn-site",
    "Properties":{"yarn.nodemanager.vmem-check-enabled":"false"},
    "Configurations":[]
  }
]
```

### After the change

The corrected `configurations` argument:
```
--configurations
[
  {
    "Classification":"spark",
    "Properties":{
      "maximizeResourceAllocation":"true"
    }
  },
  {
    "Classification":"yarn-site",
    "Properties":{
      "yarn.nodemanager.vmem-check-enabled":"false"
    }
    "Configurations":[]
  }
]
```

**Comment by biocdeniz** [comment]
Hi @MattBrauer, 

I presume you were getting this error because you are using the `.json` config file as opposed to the single line `aws emr cli`  command, correct? I decided to go with the `.yaml` file approach because that would allow me to add options to personalize other features, such as specifying a Hail version, and because it looks cleaner to the non-trained eye.

**Comment by MattBrauer** [comment]
Hi Carlos,

This is actually from the program's output, and not the .json config file. I used `config_EMR_spot.yaml` and called `sh cloudformation_hail_spot.sh`. The code above was what came out as the line `Your AWS CLI export command:`. (I simply expanded it for readability.) The original output looked like this:
```
Your AWS CLI export command:

aws emr create-cluster --applications Name=Hadoop Name=Spark --tags 'project=Ss-CFTR' 'Owner=mbrauer' 'Name=maze-hail-EMR' --ec2-attributes '{"KeyName":"modulustx-2018-08-10","InstanceProfile":"EMR_EC2_DefaultRole","SubnetId":"subnet-094f4284db8b350f7","EmrManagedSlaveSecurityGroup":"","EmrManagedMasterSecurityGroup":""}' --service-role EMR_DefaultRole --release-label emr-5.13.0 --log-uri 's3n://hail-on-emr-emrbucket-1l6c3i1wrvliu/' --name 'maze-hail-cluster' --instance-groups '[{"InstanceCount":1,"EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":50,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"MASTER","InstanceType":"m4.large","Name":"Master-Instance"},{"InstanceCount":2,"BidPrice":"0.44","EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":150,"VolumeType":"gp2"},"VolumesPerInstance":1}]},"InstanceGroupType":"CORE","InstanceType":"r4.4xlarge","Name":"Core-Group"}]' --configurations '[{"Classification":"spark","Properties":{"maximizeResourceAllocation":"true"},"Classification":"yarn-site","Properties":{"yarn.nodemanager.vmem-check-enabled":"false"},"Configurations":[]}]' --auto-scaling-role EMR_AutoScaling_DefaultRole --ebs-root-volume-size 32 --scale-down-behavior TERMINATE_AT_TASK_COMPLETION --region us-west-2
```

**Comment by biocdeniz** [comment]
Hi Matt, 

Good catch, the erroneous bracket arrangement was skipping the `maximizeResourceAllocation=True` option. I updated the repo. 
Thanks!
