### ISSUE TITLE
Bootstrap step 1 failing

### ISSUE THREAD

**Issue by alanwilter** [hms-dbmi/hail-on-AWS-spot-instances#6]
All seems fine but it failed at the end with

`Master instance (i-0b3dea4162110db17) failed attempting to download bootstrap action 1 file from S3`

I've created a bucket in the same region and I can see files being created there.
`Amazon S3 > /hail-test-s3-bucket/ > j-2IH4DWR3LJS2A`

But looking at *Bootstrap Actions* tab for cluster *j-2IH4DWR3LJS2A*, I see this message:
`s3://hms-dbmi-docs/hail_bootstrap/bootstrap_python36.sh`

Could be that the bootstrap script is trying to reach a bucket in a another region?

**Comment by alanwilter** [comment]
Analysing the logs in my s3 bucket and I found this:
`Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error `

So my suspicion was correct, I am in Europe (REGION: "eu-central-1").

Is it possible for you to make your public `s3://hms-dbmi-docs/` available to all regions?

I found [this](https://docs.aws.amazon.com/AmazonS3/latest/dev/replication.html) if it may helps

**Comment by TheEagleByte** [comment]
@alanwilter I just copied the `bootstrap_python36.sh` file into my personal S3 bucket and updated the `EMR_deploy_and_install_spot.py` to use that copy instead. It worked.

**Comment by alanwilter** [comment]
Thanks @TheEagleByte. I ended up doing precisely this in my forked version.
